// MAAT — Monitoring et Audit des Accès pour la Traçabilité
// Copyright (C) 2026  Pierre-Nicolas MARTIN
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. This program is distributed WITHOUT ANY WARRANTY; see
// the GNU General Public License <https://www.gnu.org/licenses/> for details.

using System.Collections.Generic;

namespace MAAT.App.Localization;

/// <summary>
/// Catalogues de traduction (clé → texte) par code de langue. Pour ajouter une
/// langue : créer un dictionnaire et l'enregistrer dans <see cref="Catalogs"/>.
/// </summary>
public static class Strings
{
    // Construit à la PREMIÈRE lecture (et non à l'initialisation statique) : sinon,
    // l'ordre textuel ferait capturer Fr/En encore nuls → valeurs de catalogue nulles.
    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>? _catalogs;

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Catalogs =>
        _catalogs ??= new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["fr"] = Fr,
            ["en"] = En,
        };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // — Menu —
        ["Menu_File"] = "Fichier",
        ["Menu_NewAudit"] = "Nouvel audit…",
        ["Menu_OpenProject"] = "Ouvrir un projet…",
        ["Menu_ExportTo"] = "Exporter vers",
        ["Menu_ExportHtml"] = "Rapport HTML…",
        ["Menu_ExportCsv"] = "CSV…",
        ["Menu_SaveProject"] = "Enregistrer le projet sous…",
        ["Menu_Quit"] = "Quitter",
        ["Menu_Preferences"] = "Préférences",
        ["Menu_Display"] = "Affichage",
        ["Menu_ThemeAuto"] = "Auto (système)",
        ["Menu_ThemeLight"] = "Thème clair",
        ["Menu_ThemeDark"] = "Thème sombre",
        ["Menu_Language"] = "Langue",
        ["Menu_LangAuto"] = "Auto (système)",
        ["Menu_Help"] = "Aide",
        ["Menu_Guide"] = "Guide d'utilisation…",
        ["Menu_About"] = "À propos…",
        // — En-tête / accueil —
        ["Win_Title"] = "MAAT — Audit de système de fichiers",
        ["Access_All"] = "Tous les éléments",
        ["Header_Subtitle"] = "Monitoring et Audit des Accès pour la Traçabilité",
        ["Header_Tag"] = "AUDIT NTFS · VOLUMÉTRIE · TRAÇABILITÉ",
        ["Footer_Confidential"] = "Les résultats peuvent contenir des informations sensibles ou confidentielles. · GPLv3",
        ["Empty_Title"] = "Auditez vos systèmes de fichiers.",
        ["Empty_Body"] = "Droits NTFS et volumétrie, en clair. Lancez un nouvel audit ou rouvrez un projet .maat existant.",
        ["Btn_NewAudit"] = "Nouvel audit",
        ["Btn_OpenProject"] = "Ouvrir un projet",
        // — Configuration —
        ["Cfg_WinTitle"] = "Nouvel audit — MAAT",
        ["Cfg_Folder"] = "Dossier à auditer",
        ["Cfg_FolderHint"] = "Chemin local ou UNC (ex. C:\\Partages ou \\\\serveur\\partage).",
        ["Cfg_Browse"] = "Parcourir…",
        ["Cfg_Depth"] = "Profondeur d'analyse",
        ["Cfg_Numbering"] = "NUMÉROTATION DES NIVEAUX",
        ["Cfg_Root"] = "Racine",
        ["Cfg_Subfolder"] = "Sous-dossier",
        ["Cfg_DepthHint"] = "« Illimité » parcourt toute l'arborescence ; sinon, le numéro choisi est le dernier niveau inclus.",
        ["Cfg_Type"] = "Type d'audit",
        ["Cfg_TypeFolders"] = "Inclure les dossiers",
        ["Cfg_TypeFiles"] = "Inclure les dossiers et les fichiers",
        ["Cfg_LongHint"] = "(Temps d'exécution plus long)",
        ["Cfg_Content"] = "Contenu de l'audit",
        ["Cfg_ContentRights"] = "Analyser les droits",
        ["Cfg_ContentSize"] = "Analyser la volumétrie",
        ["Cfg_ContentBoth"] = "Analyser les droits et la volumétrie",
        ["Cfg_IdScope"] = "ÉTENDUE DES IDENTITÉS",
        ["Cfg_IncludeLocal"] = "Inclure les comptes locaux et intégrés",
        ["Cfg_IncludeLocalHint"] = "Décoché : seules les identités du domaine Active Directory sont auditées (exclut BUILTIN, AUTORITÉ NT, comptes de la machine, Tout le monde…).",
        ["Cfg_ExportHint"] = "Les exports CSV / HTML se font après l'audit (menu Fichier → Exporter).",
        ["Cfg_Start"] = "Lancer l'audit",
        ["Common_Cancel"] = "Annuler",
        ["Common_Close"] = "Fermer",
        ["Cfg_PathError"] = "Dossier introuvable ou inaccessible.",
        ["Cfg_PathInvalid"] = "Chemin invalide : {0}",
        // — Profondeur (options) —
        ["Depth_Unlimited"] = "♾  Illimité (toute l'arborescence)",
        ["Depth_RootOnly"] = "0  ·  Racine seulement",
        ["Depth_Level1"] = "{0}  ·  Racine + {0} sous-niveau",
        ["Depth_LevelN"] = "{0}  ·  Racine + {0} sous-niveaux",
        // — Progression —
        ["Prog_Title"] = "Audit en cours",
        ["Prog_Global"] = "PROGRESSION GLOBALE",
        ["Prog_Init"] = "Initialisation…",
        ["Prog_Estimating"] = "Estimation…",
        ["Prog_Done"] = "Terminé",
        ["Prog_Cancelled"] = "Annulé",
        ["Prog_Cancelling"] = "Annulation…",
        ["Prog_Error"] = "Erreur",
        ["Prog_ProjectLoaded"] = "Projet chargé",
        ["Prog_EtaLeft"] = "≈ {0} restant",
        ["Prog_Elapsed"] = "{0} écoulé",
        ["Phase_EnumFolders"] = "Énumération des dossiers",
        ["Phase_EnumFiles"] = "Énumération des fichiers",
        ["Phase_ReadAcl"] = "Lecture des droits NTFS",
        ["Phase_ResolveAd"] = "Résolution des identités AD",
        ["Phase_Sizes"] = "Calcul de la volumétrie",
        ["Phase_Export"] = "Export",
        ["Phase_Default"] = "Traitement",
        // — Paramètres (résumé) —
        ["Param_Folders"] = "dossiers",
        ["Param_FoldersFiles"] = "dossiers + fichiers",
        ["Param_RightsSize"] = "droits + volumétrie",
        ["Param_Rights"] = "droits NTFS",
        ["Param_Size"] = "volumétrie",
        ["Param_DepthUnlimited"] = "profondeur illimitée",
        ["Param_DepthRoot"] = "racine seule",
        ["Param_Depth"] = "profondeur {0}",
        // — Busy / exports —
        ["Busy_ExportCsv"] = "Export CSV en cours",
        ["Busy_ExportHtml"] = "Génération du rapport HTML",
        ["Busy_Save"] = "Enregistrement du projet",
        ["Busy_Writing"] = "Écriture de {0}…",
        ["Busy_Wait"] = "Veuillez patienter…",
        ["Busy_BigHint"] = "Les très gros volumes peuvent prendre un moment.",
        ["Msg_ExportCsv"] = "Export CSV : {0}",
        ["Msg_ExportHtml"] = "Rapport HTML : {0}",
        ["Msg_Saved"] = "Projet enregistré : {0}",
        ["Dlg_SaveProject"] = "Enregistrer le projet MAAT",
        ["Dlg_OpenProject"] = "Ouvrir un projet MAAT",
        ["Filter_MaatOpen"] = "Projet MAAT (*.maat)|*.maat|Tous les fichiers (*.*)|*.*",
        ["Filter_Maat"] = "Projet MAAT (*.maat)|*.maat",
        ["Filter_Csv"] = "Fichier CSV (*.csv)|*.csv",
        ["Filter_Html"] = "Rapport HTML (*.html)|*.html",
        ["Filter_LogCsv"] = "Journal CSV (*.csv)|*.csv",
        ["Dlg_ExportCsv"] = "Exporter en CSV",
        ["Dlg_ExportHtml"] = "Exporter en rapport HTML",
        ["Dlg_PickFolder"] = "Sélectionner le dossier à auditer",
        // — Résultats / scan —
        ["Scan_Audited"] = "Audité le {0}",
        ["Scan_AuditedPrefix"] = "Audité le",
        ["Scan_Search"] = "Rechercher un dossier, un fichier, un chemin…",
        ["Scan_Folders"] = "DOSSIERS",
        ["Scan_Files"] = "FICHIERS",
        ["Scan_TotalSize"] = "VOLUMÉTRIE TOTALE",
        ["Scan_Aces"] = "ENTRÉES ACL",
        ["Scan_Identities"] = "IDENTITÉS →",
        ["Scan_AllRights"] = "Tous les droits",
        ["Scan_Explicit"] = "Explicites",
        ["Scan_Inherited"] = "Hérités",
        ["Scan_AccessTip"] = "Afficher les éléments accessibles à une identité (accès direct ou via groupe AD)",
        ["Scan_AclTip"] = "Cliquer pour afficher/masquer les droits",
        ["Scan_Loading"] = "Chargement…",
        ["Ace_Allow"] = "Autoriser",
        ["Ace_Deny"] = "Refuser",
        ["Ace_Member"] = "membre",
        ["Ace_Members"] = "membres",
        ["Ace_Inherited"] = "Hérité",
        ["Ace_Explicit"] = "Explicite",
        ["Confirm_Title"] = "MAAT — Enregistrer le projet",
        ["Confirm_Discard"] = "L'audit en cours n'est pas enregistré.\nSouhaitez-vous enregistrer le projet avant de continuer ?",
        ["Name_Rights"] = "Audit_Droits",
        ["Name_RightsSize"] = "Audit_Droits_Volumetrie",
        ["Name_Size"] = "Audit_Volumetrie",
        // — Fenêtre Identités —
        ["Id_WinTitle"] = "Identités — Groupes AD & Utilisateurs",
        ["Id_Label"] = "IDENTITÉS",
        ["Id_Title"] = "Groupes AD & Utilisateurs",
        ["Id_Groups"] = "Groupes AD",
        ["Id_Users"] = "Utilisateurs / Identités directes",
        ["Id_ExportCsv"] = "Exporter en CSV",
        ["Id_Summary"] = "{0} groupe(s) AD · {1} utilisateur(s) / identité(s)",
        ["Id_DlgExport"] = "Exporter les identités",
        ["Id_FileName"] = "Identites_AD",
        ["Id_CsvHeader"] = "\"Type\";\"Identité\";\"Membre\";\"Nb éléments\"",
        ["Id_CsvGroup"] = "Groupe",
        ["Id_CsvUser"] = "Utilisateur",
        ["Id_CsvNoMember"] = "(aucun membre)",
        ["Id_Item"] = "élément",
        ["Id_Items"] = "éléments",
        // — Rapport d'analyse —
        ["Rep_WinTitle"] = "Rapport d'analyse de l'audit",
        ["Rep_Label"] = "RAPPORT D'ANALYSE",
        ["Rep_Title"] = "Synthèse de l'audit",
        ["Rep_FinishedOn"] = "Audit terminé le ",
        ["Rep_Summary"] = "SYNTHÈSE",
        ["Rep_Issues"] = "ÉLÉMENTS NON AUDITÉS",
        ["Rep_NoIssues"] = "Tous les éléments rencontrés ont pu être audités.",
        ["Rep_AllAudited"] = "Aucun élément n'a été ignoré : l'audit est complet.",
        ["Rep_IssuesSummary"] = "{0} élément(s) non audité(s) — {1} erreur(s), {2} avertissement(s)",
        ["Rep_ExportLog"] = "Exporter le journal",
        ["Rep_DlgExportLog"] = "Exporter le journal d'audit",
        ["Rep_LogExported"] = "Journal exporté : {0}",
        ["Rep_Stat_Folders"] = "Dossiers",
        ["Rep_Stat_Files"] = "Fichiers",
        ["Rep_Stat_Aces"] = "ACE",
        ["Rep_Stat_Size"] = "Volumétrie totale",
        ["Rep_Stat_Junctions"] = "Jonctions",
        ["Rep_Stat_Duration"] = "Durée",
        ["Rep_Stat_AdResolved"] = "Identités AD résolues",
        ["Rep_Stat_Ad"] = "Active Directory",
        ["Rep_Stat_AdOff"] = "Indisponible",
        ["Rep_Stat_Denied"] = "Accès refusés",
        ["Sev_Error"] = "Erreur",
        ["Sev_Warn"] = "Avertissement",
        ["Rep_LogHeader"] = "Horodatage;Gravité;Motif;Chemin",
        ["Log_AccessDenied"] = "Accès refusé",
        ["Log_PathNotFound"] = "Chemin introuvable",
        ["Log_ReparseSkipped"] = "Jonction / lien ignoré",
        ["Log_ReadError"] = "Erreur de lecture",
        ["Log_AclUnreadable"] = "ACL illisible",
        ["Log_AceError"] = "Erreur sur une ACE",
        ["Log_AdResolution"] = "Résolution Active Directory",
        ["Log_Other"] = "Évènement",
        // — À propos —
        ["About_Tagline"] = "Audit avancé de systèmes de fichiers : droits NTFS (héritage, Autoriser/Refuser, groupes AD) et volumétrie.",
        ["About_License"] = "LICENCE GNU GPL v3",
        ["About_LicenseBody"] = "Logiciel libre redistribuable selon les termes de la GPLv3 — ",
        ["About_Warranty"] = "Ce programme est fourni « en l'état », sans aucune garantie, dans la mesure permise par la loi. L'auteur ne saurait être tenu responsable des dommages résultant de son utilisation.",
        ["About_Confidential"] = "Les résultats peuvent contenir des informations sensibles ou confidentielles.",
        ["About_Version"] = "Version {0}",
        ["About_WinTitle"] = "À propos de MAAT",
        // — Guide —
        ["Guide_WinTitle"] = "Guide d'utilisation — MAAT",
        ["Guide_HdrLabel"] = "AIDE",
        ["Guide_HdrTitle"] = "Guide d'utilisation",
        ["Guide_HdrSub"] = "Auditer les droits NTFS et la volumétrie d'un système de fichiers, du paramétrage à l'export.",
        ["Guide_S1Label"] = "01 · DÉMARRER",
        ["Guide_S1Title"] = "Lancer un audit",
        ["Guide_S1Body"] = "Menu Fichier → Nouvel audit (ou le bouton de l'écran d'accueil). Indiquez le dossier à auditer : un chemin local (C:\\Partages) ou un partage réseau UNC (\\\\serveur\\partage). Le bouton Parcourir ouvre un sélecteur de dossier.",
        ["Guide_S2Label"] = "02 · PROFONDEUR",
        ["Guide_S2Title"] = "Profondeur d'analyse",
        ["Guide_S2Body"] = "Choisit jusqu'où descendre dans l'arborescence. La racine est le niveau 0, ses sous-dossiers le niveau 1, etc. « Illimité » parcourt tout ; un numéro N limite au dernier niveau inclus.\n\nNote : la volumétrie reflète toujours l'intégralité d'un sous-arbre, même au-delà de la profondeur d'affichage.",
        ["Guide_S3Label"] = "03 · CONTENU",
        ["Guide_S3Title"] = "Type, contenu et étendue des identités",
        ["Guide_S3Body"] = "Type : auditer les dossiers seuls (rapide) ou dossiers + fichiers (plus long). Contenu : droits NTFS, volumétrie, ou les deux.\n\nÉtendue des identités (audit des droits) : cochée, inclut les comptes locaux et intégrés (BUILTIN, AUTORITÉ NT, administrateurs locaux, Tout le monde…). Décochée, ne conserve que les identités du domaine Active Directory.",
        ["Guide_S4Label"] = "04 · RÉSULTATS",
        ["Guide_S4Title"] = "Lire l'arborescence",
        ["Guide_S4Body"] = "L'arbre EST le résultat. Dépliez un dossier avec le chevron ; cliquez le nom d'un élément pour afficher / masquer ses droits NTFS en ligne (identité, type Autoriser/Refuser, autorisations, portée, héritage et source). Une capsule indique l'extension d'un fichier, et sa volumétrie s'affiche à droite.\n\nDans une ligne de droits, un groupe AD affiche ses membres au clic sur « N membres ».",
        ["Guide_S5Label"] = "05 · RECHERCHE & FILTRES",
        ["Guide_S5Title"] = "Retrouver et filtrer",
        ["Guide_S5Body"] = "Recherche : tapez un nom de dossier, de fichier ou un chemin pour basculer en liste à plat des correspondances.\n\nContrôle d'accès : sélectionnez une identité pour ne lister que les éléments auxquels elle a accès (directement ou via un groupe AD).\n\nFiltre des droits : Tous, Explicites ou Hérités, pour ne montrer que les éléments concernés.",
        ["Guide_S6Label"] = "06 · IDENTITÉS & RAPPORT",
        ["Guide_S6Title"] = "Synthèse des identités et rapport d'analyse",
        ["Guide_S6Body"] = "La carte Identités ouvre la liste des groupes AD (avec leurs membres) et des utilisateurs rencontrés. À la fin d'un audit, un rapport d'analyse récapitule les statistiques et liste les éléments qui n'ont pas pu être audités (accès refusés, jonctions…), avec export du journal.",
        ["Guide_S7Label"] = "07 · EXPORTS & PROJETS",
        ["Guide_S7Title"] = "Exporter et enregistrer",
        ["Guide_S7Body"] = "Menu Fichier → Exporter : rapport HTML interactif (recherche, filtres, thème clair/sombre) ou CSV détaillé. Enregistrer le projet crée un fichier .maat rouvrable plus tard (Fichier → Ouvrir un projet) sans re-scanner.",
        ["Guide_S8Label"] = "08 · APPARENCE & CONFIDENTIALITÉ",
        ["Guide_S8Title"] = "Thème et confidentialité",
        ["Guide_S8Body"] = "Menu Préférences → Affichage bascule entre Auto (système), thème clair et thème sombre.\n\nLes résultats peuvent contenir des informations sensibles ou confidentielles. La base temporaire d'un audit non enregistré est détruite à la fermeture.",
        ["Guide_S9Label"] = "09 · COMPRENDRE LES DROITS NTFS",
        ["Guide_S9Title"] = "Lire une ligne d'autorisation",
        ["Guide_S9Body"] = "Identité : le compte ou groupe concerné (DOMAINE\\groupe, BUILTIN\\…). Type : Autoriser ou Refuser — un Refuser l'emporte toujours sur un Autoriser. Autorisations : les droits accordés (Contrôle total, Modifier, Lecture…).\n\nPortée : à quoi le droit s'applique (ce dossier, ses sous-dossiers, ses fichiers). Hérité / Explicite : un droit hérité provient d'un dossier parent ; la source indique lequel. Un droit explicite est défini sur l'élément lui-même.\n\nLe filtre « Explicites / Hérités » aide à repérer les dossiers où des droits ont été posés manuellement (souvent les points d'attention d'un audit).",
        ["Guide_S10Label"] = "10 · CAS PARTICULIERS",
        ["Guide_S10Title"] = "OneDrive, jonctions et accès refusés",
        ["Guide_S10Body"] = "OneDrive / fichiers cloud : les dossiers synchronisés sont parcourus normalement (leur volumétrie logique est comptée sans téléchargement). Jonctions et liens symboliques : audités pour leurs droits mais non parcourus, afin d'éviter les boucles et les doublons.\n\nAccès refusés : un dossier inaccessible est journalisé et l'audit continue. Sa volumétrie est alors marquée ≈ (partielle). Le rapport de fin d'audit récapitule tous ces éléments non audités, avec leur motif, et permet d'exporter le journal.",
        ["Guide_S11Label"] = "11 · BON À SAVOIR",
        ["Guide_S11Title"] = "Astuces et performances",
        ["Guide_S11Body"] = "• Un fichier .maat se rouvre d'un double-clic depuis l'Explorateur.\n• L'audit s'exécute sous votre identité Windows : vous ne voyez que ce à quoi vous avez accès.\n• Pour de très gros volumes, limitez la profondeur ou n'analysez que les dossiers : c'est nettement plus rapide. L'analyse de la volumétrie reste, elle, toujours complète.\n• Hors domaine Active Directory, la résolution des groupes est ignorée sans bloquer l'audit.",
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // — Menu —
        ["Menu_File"] = "File",
        ["Menu_NewAudit"] = "New audit…",
        ["Menu_OpenProject"] = "Open project…",
        ["Menu_ExportTo"] = "Export to",
        ["Menu_ExportHtml"] = "HTML report…",
        ["Menu_ExportCsv"] = "CSV…",
        ["Menu_SaveProject"] = "Save project as…",
        ["Menu_Quit"] = "Quit",
        ["Menu_Preferences"] = "Preferences",
        ["Menu_Display"] = "Appearance",
        ["Menu_ThemeAuto"] = "Auto (system)",
        ["Menu_ThemeLight"] = "Light theme",
        ["Menu_ThemeDark"] = "Dark theme",
        ["Menu_Language"] = "Language",
        ["Menu_LangAuto"] = "Auto (system)",
        ["Menu_Help"] = "Help",
        ["Menu_Guide"] = "User guide…",
        ["Menu_About"] = "About…",
        // — Header / home —
        ["Win_Title"] = "MAAT — File system audit",
        ["Access_All"] = "All items",
        ["Header_Subtitle"] = "Monitoring and Access Auditing for Traceability",
        ["Header_Tag"] = "NTFS AUDIT · VOLUMETRY · TRACEABILITY",
        ["Footer_Confidential"] = "Results may contain sensitive or confidential information. · GPLv3",
        ["Empty_Title"] = "Audit your file systems.",
        ["Empty_Body"] = "NTFS permissions and volumetry, made clear. Start a new audit or reopen an existing .maat project.",
        ["Btn_NewAudit"] = "New audit",
        ["Btn_OpenProject"] = "Open project",
        // — Configuration —
        ["Cfg_WinTitle"] = "New audit — MAAT",
        ["Cfg_Folder"] = "Folder to audit",
        ["Cfg_FolderHint"] = "Local or UNC path (e.g. C:\\Shares or \\\\server\\share).",
        ["Cfg_Browse"] = "Browse…",
        ["Cfg_Depth"] = "Analysis depth",
        ["Cfg_Numbering"] = "LEVEL NUMBERING",
        ["Cfg_Root"] = "Root",
        ["Cfg_Subfolder"] = "Subfolder",
        ["Cfg_DepthHint"] = "\"Unlimited\" walks the whole tree; otherwise the chosen number is the last level included.",
        ["Cfg_Type"] = "Audit type",
        ["Cfg_TypeFolders"] = "Include folders",
        ["Cfg_TypeFiles"] = "Include folders and files",
        ["Cfg_LongHint"] = "(Longer execution time)",
        ["Cfg_Content"] = "Audit content",
        ["Cfg_ContentRights"] = "Analyze permissions",
        ["Cfg_ContentSize"] = "Analyze volumetry",
        ["Cfg_ContentBoth"] = "Analyze permissions and volumetry",
        ["Cfg_IdScope"] = "IDENTITY SCOPE",
        ["Cfg_IncludeLocal"] = "Include local and built-in accounts",
        ["Cfg_IncludeLocalHint"] = "Unchecked: only Active Directory domain identities are audited (excludes BUILTIN, NT AUTHORITY, machine accounts, Everyone…).",
        ["Cfg_ExportHint"] = "CSV / HTML exports are done after the audit (File → Export).",
        ["Cfg_Start"] = "Start audit",
        ["Common_Cancel"] = "Cancel",
        ["Common_Close"] = "Close",
        ["Cfg_PathError"] = "Folder not found or inaccessible.",
        ["Cfg_PathInvalid"] = "Invalid path: {0}",
        // — Depth —
        ["Depth_Unlimited"] = "♾  Unlimited (whole tree)",
        ["Depth_RootOnly"] = "0  ·  Root only",
        ["Depth_Level1"] = "{0}  ·  Root + {0} sublevel",
        ["Depth_LevelN"] = "{0}  ·  Root + {0} sublevels",
        // — Progress —
        ["Prog_Title"] = "Audit in progress",
        ["Prog_Global"] = "OVERALL PROGRESS",
        ["Prog_Init"] = "Initializing…",
        ["Prog_Estimating"] = "Estimating…",
        ["Prog_Done"] = "Done",
        ["Prog_Cancelled"] = "Cancelled",
        ["Prog_Cancelling"] = "Cancelling…",
        ["Prog_Error"] = "Error",
        ["Prog_ProjectLoaded"] = "Project loaded",
        ["Prog_EtaLeft"] = "≈ {0} left",
        ["Prog_Elapsed"] = "{0} elapsed",
        ["Phase_EnumFolders"] = "Enumerating folders",
        ["Phase_EnumFiles"] = "Enumerating files",
        ["Phase_ReadAcl"] = "Reading NTFS permissions",
        ["Phase_ResolveAd"] = "Resolving AD identities",
        ["Phase_Sizes"] = "Computing sizes",
        ["Phase_Export"] = "Export",
        ["Phase_Default"] = "Processing",
        // — Parameters summary —
        ["Param_Folders"] = "folders",
        ["Param_FoldersFiles"] = "folders + files",
        ["Param_RightsSize"] = "permissions + size",
        ["Param_Rights"] = "NTFS permissions",
        ["Param_Size"] = "size",
        ["Param_DepthUnlimited"] = "unlimited depth",
        ["Param_DepthRoot"] = "root only",
        ["Param_Depth"] = "depth {0}",
        // — Busy / exports —
        ["Busy_ExportCsv"] = "Exporting CSV",
        ["Busy_ExportHtml"] = "Generating HTML report",
        ["Busy_Save"] = "Saving project",
        ["Busy_Writing"] = "Writing {0}…",
        ["Busy_Wait"] = "Please wait…",
        ["Busy_BigHint"] = "Very large volumes may take a while.",
        ["Msg_ExportCsv"] = "CSV export: {0}",
        ["Msg_ExportHtml"] = "HTML report: {0}",
        ["Msg_Saved"] = "Project saved: {0}",
        ["Dlg_SaveProject"] = "Save MAAT project",
        ["Dlg_OpenProject"] = "Open a MAAT project",
        ["Filter_MaatOpen"] = "MAAT project (*.maat)|*.maat|All files (*.*)|*.*",
        ["Filter_Maat"] = "MAAT project (*.maat)|*.maat",
        ["Filter_Csv"] = "CSV file (*.csv)|*.csv",
        ["Filter_Html"] = "HTML report (*.html)|*.html",
        ["Filter_LogCsv"] = "CSV log (*.csv)|*.csv",
        ["Dlg_ExportCsv"] = "Export to CSV",
        ["Dlg_ExportHtml"] = "Export to HTML report",
        ["Dlg_PickFolder"] = "Select the folder to audit",
        // — Results / scan —
        ["Scan_Audited"] = "Audited on {0}",
        ["Scan_AuditedPrefix"] = "Audited on",
        ["Scan_Search"] = "Search a folder, a file, a path…",
        ["Scan_Folders"] = "FOLDERS",
        ["Scan_Files"] = "FILES",
        ["Scan_TotalSize"] = "TOTAL SIZE",
        ["Scan_Aces"] = "ACL ENTRIES",
        ["Scan_Identities"] = "IDENTITIES →",
        ["Scan_AllRights"] = "All permissions",
        ["Scan_Explicit"] = "Explicit",
        ["Scan_Inherited"] = "Inherited",
        ["Scan_AccessTip"] = "Show items accessible to an identity (directly or via an AD group)",
        ["Scan_AclTip"] = "Click to show/hide permissions",
        ["Scan_Loading"] = "Loading…",
        ["Ace_Allow"] = "Allow",
        ["Ace_Deny"] = "Deny",
        ["Ace_Member"] = "member",
        ["Ace_Members"] = "members",
        ["Ace_Inherited"] = "Inherited",
        ["Ace_Explicit"] = "Explicit",
        ["Confirm_Title"] = "MAAT — Save project",
        ["Confirm_Discard"] = "The current audit is not saved.\nDo you want to save the project before continuing?",
        ["Name_Rights"] = "Audit_Permissions",
        ["Name_RightsSize"] = "Audit_Permissions_Size",
        ["Name_Size"] = "Audit_Size",
        // — Identities window —
        ["Id_WinTitle"] = "Identities — AD Groups & Users",
        ["Id_Label"] = "IDENTITIES",
        ["Id_Title"] = "AD Groups & Users",
        ["Id_Groups"] = "AD Groups",
        ["Id_Users"] = "Users / Direct identities",
        ["Id_ExportCsv"] = "Export to CSV",
        ["Id_Summary"] = "{0} AD group(s) · {1} user(s) / identity(ies)",
        ["Id_DlgExport"] = "Export identities",
        ["Id_FileName"] = "Identities_AD",
        ["Id_CsvHeader"] = "\"Type\";\"Identity\";\"Member\";\"Count\"",
        ["Id_CsvGroup"] = "Group",
        ["Id_CsvUser"] = "User",
        ["Id_CsvNoMember"] = "(no member)",
        ["Id_Item"] = "item",
        ["Id_Items"] = "items",
        // — Analysis report —
        ["Rep_WinTitle"] = "Audit analysis report",
        ["Rep_Label"] = "ANALYSIS REPORT",
        ["Rep_Title"] = "Audit summary",
        ["Rep_FinishedOn"] = "Audit finished on ",
        ["Rep_Summary"] = "SUMMARY",
        ["Rep_Issues"] = "ITEMS NOT AUDITED",
        ["Rep_NoIssues"] = "All encountered items could be audited.",
        ["Rep_AllAudited"] = "No item was skipped: the audit is complete.",
        ["Rep_IssuesSummary"] = "{0} item(s) not audited — {1} error(s), {2} warning(s)",
        ["Rep_ExportLog"] = "Export log",
        ["Rep_DlgExportLog"] = "Export audit log",
        ["Rep_LogExported"] = "Log exported: {0}",
        ["Rep_Stat_Folders"] = "Folders",
        ["Rep_Stat_Files"] = "Files",
        ["Rep_Stat_Aces"] = "ACE",
        ["Rep_Stat_Size"] = "Total size",
        ["Rep_Stat_Junctions"] = "Junctions",
        ["Rep_Stat_Duration"] = "Duration",
        ["Rep_Stat_AdResolved"] = "Resolved AD identities",
        ["Rep_Stat_Ad"] = "Active Directory",
        ["Rep_Stat_AdOff"] = "Unavailable",
        ["Rep_Stat_Denied"] = "Access denied",
        ["Sev_Error"] = "Error",
        ["Sev_Warn"] = "Warning",
        ["Rep_LogHeader"] = "Timestamp;Severity;Reason;Path",
        ["Log_AccessDenied"] = "Access denied",
        ["Log_PathNotFound"] = "Path not found",
        ["Log_ReparseSkipped"] = "Junction / link skipped",
        ["Log_ReadError"] = "Read error",
        ["Log_AclUnreadable"] = "Unreadable ACL",
        ["Log_AceError"] = "ACE error",
        ["Log_AdResolution"] = "Active Directory resolution",
        ["Log_Other"] = "Event",
        // — About —
        ["About_Tagline"] = "Advanced file-system auditing: NTFS permissions (inheritance, Allow/Deny, AD groups) and volumetry.",
        ["About_License"] = "GNU GPL v3 LICENSE",
        ["About_LicenseBody"] = "Free software redistributable under the terms of the GPLv3 — ",
        ["About_Warranty"] = "This program is provided \"as is\", without any warranty, to the extent permitted by law. The author shall not be held liable for any damage resulting from its use.",
        ["About_Confidential"] = "Results may contain sensitive or confidential information.",
        ["About_Version"] = "Version {0}",
        ["About_WinTitle"] = "About MAAT",
        // — Guide —
        ["Guide_WinTitle"] = "User guide — MAAT",
        ["Guide_HdrLabel"] = "HELP",
        ["Guide_HdrTitle"] = "User guide",
        ["Guide_HdrSub"] = "Audit NTFS permissions and volumetry of a file system, from setup to export.",
        ["Guide_S1Label"] = "01 · GET STARTED",
        ["Guide_S1Title"] = "Run an audit",
        ["Guide_S1Body"] = "Menu File → New audit (or the home screen button). Enter the folder to audit: a local path (C:\\Shares) or a UNC network share (\\\\server\\share). The Browse button opens a folder picker.",
        ["Guide_S2Label"] = "02 · DEPTH",
        ["Guide_S2Title"] = "Analysis depth",
        ["Guide_S2Body"] = "Chooses how deep to descend into the tree. The root is level 0, its subfolders level 1, etc. “Unlimited” walks everything; a number N stops at the last included level.\n\nNote: volumetry always reflects the entire subtree, even beyond the displayed depth.",
        ["Guide_S3Label"] = "03 · CONTENT",
        ["Guide_S3Title"] = "Type, content and identity scope",
        ["Guide_S3Body"] = "Type: audit folders only (fast) or folders + files (longer). Content: NTFS permissions, volumetry, or both.\n\nIdentity scope (permissions audit): checked, it includes local and built-in accounts (BUILTIN, NT AUTHORITY, local administrators, Everyone…). Unchecked, it keeps only Active Directory domain identities.",
        ["Guide_S4Label"] = "04 · RESULTS",
        ["Guide_S4Title"] = "Reading the tree",
        ["Guide_S4Body"] = "The tree IS the result. Expand a folder with the chevron; click an item's name to show / hide its NTFS permissions inline (identity, Allow/Deny type, permissions, scope, inheritance and source). A capsule shows a file's extension, and its volumetry is displayed on the right.\n\nIn a permission row, an AD group reveals its members when you click “N members”.",
        ["Guide_S5Label"] = "05 · SEARCH & FILTERS",
        ["Guide_S5Title"] = "Find and filter",
        ["Guide_S5Body"] = "Search: type a folder name, a file name or a path to switch to a flat list of matches.\n\nAccess control: select an identity to list only the items it can access (directly or via an AD group).\n\nPermissions filter: All, Explicit or Inherited, to show only the relevant items.",
        ["Guide_S6Label"] = "06 · IDENTITIES & REPORT",
        ["Guide_S6Title"] = "Identity summary and analysis report",
        ["Guide_S6Body"] = "The Identities card opens the list of AD groups (with their members) and the users encountered. At the end of an audit, an analysis report summarizes the statistics and lists the items that could not be audited (access denied, junctions…), with log export.",
        ["Guide_S7Label"] = "07 · EXPORTS & PROJECTS",
        ["Guide_S7Title"] = "Export and save",
        ["Guide_S7Body"] = "Menu File → Export: interactive HTML report (search, filters, light/dark theme) or detailed CSV. Save project creates a .maat file that can be reopened later (File → Open a project) without re-scanning.",
        ["Guide_S8Label"] = "08 · APPEARANCE & CONFIDENTIALITY",
        ["Guide_S8Title"] = "Theme and confidentiality",
        ["Guide_S8Body"] = "Menu Preferences → Display switches between Auto (system), light theme and dark theme.\n\nResults may contain sensitive or confidential information. The temporary database of an unsaved audit is destroyed on close.",
        ["Guide_S9Label"] = "09 · UNDERSTANDING NTFS PERMISSIONS",
        ["Guide_S9Title"] = "Reading a permission row",
        ["Guide_S9Body"] = "Identity: the account or group concerned (DOMAIN\\group, BUILTIN\\…). Type: Allow or Deny — a Deny always overrides an Allow. Permissions: the granted rights (Full control, Modify, Read…).\n\nScope: what the right applies to (this folder, its subfolders, its files). Inherited / Explicit: an inherited right comes from a parent folder; the source indicates which one. An explicit right is set on the item itself.\n\nThe “Explicit / Inherited” filter helps spot folders where rights were set manually (often the focus points of an audit).",
        ["Guide_S10Label"] = "10 · SPECIAL CASES",
        ["Guide_S10Title"] = "OneDrive, junctions and access denied",
        ["Guide_S10Body"] = "OneDrive / cloud files: synced folders are walked normally (their logical volumetry is counted without downloading). Junctions and symbolic links: audited for their permissions but not walked, to avoid loops and duplicates.\n\nAccess denied: an inaccessible folder is logged and the audit continues. Its volumetry is then marked ≈ (partial). The end-of-audit report lists all these non-audited items, with their reason, and lets you export the log.",
        ["Guide_S11Label"] = "11 · GOOD TO KNOW",
        ["Guide_S11Title"] = "Tips and performance",
        ["Guide_S11Body"] = "• A .maat file reopens with a double-click from Explorer.\n• The audit runs under your Windows identity: you only see what you can access.\n• For very large volumes, limit the depth or audit folders only: it is markedly faster. Volumetry analysis itself always stays complete.\n• Outside an Active Directory domain, group resolution is skipped without blocking the audit.",
    };
}