// MAAT — Monitoring et Audit des Accès pour la Traçabilité
// Copyright (C) 2026  Pierre-Nicolas MARTIN
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. This program is distributed WITHOUT ANY WARRANTY; see
// the GNU General Public License <https://www.gnu.org/licenses/> for details.

using System.Collections.Generic;

namespace MAAT.App.Localization;

/// <summary>
/// Catalogues de traduction (clé → texte) par code de langue. Pour ajouter une
/// langue : créer un dictionnaire et l'enregistrer dans <see cref="Catalogs"/>.
/// </summary>
public static class Strings
{
    // Construit à la PREMIÈRE lecture (et non à l'initialisation statique) : sinon,
    // l'ordre textuel ferait capturer Fr/En encore nuls → valeurs de catalogue nulles.
    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>? _catalogs;

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Catalogs =>
        _catalogs ??= new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["fr"] = Fr,
            ["en"] = En,
        };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // — Menu —
        ["Menu_File"] = "Fichier",
        ["Menu_NewAudit"] = "Nouvel audit…",
        ["Menu_OpenProject"] = "Ouvrir un projet…",
        ["Menu_ExportTo"] = "Exporter vers",
        ["Menu_ExportHtml"] = "Rapport HTML…",
        ["Menu_ExportCsv"] = "CSV…",
        ["Menu_SaveProject"] = "Enregistrer le projet sous…",
        ["Menu_Quit"] = "Quitter",
        ["Menu_Preferences"] = "Préférences",
        ["Menu_Display"] = "Affichage",
        ["Menu_ThemeAuto"] = "Auto (système)",
        ["Menu_ThemeLight"] = "Thème clair",
        ["Menu_ThemeDark"] = "Thème sombre",
        ["Menu_Language"] = "Langue",
        ["Menu_LangAuto"] = "Auto (système)",
        ["Menu_Help"] = "Aide",
        ["Menu_Guide"] = "Guide d'utilisation…",
        ["Menu_About"] = "À propos…",
        // — En-tête / accueil —
        ["Win_Title"] = "MAAT — Audit de système de fichiers",
        ["Access_All"] = "Tous les éléments",
        ["Header_Subtitle"] = "Monitoring et Audit des Accès pour la Traçabilité",
        ["Header_Tag"] = "AUDIT NTFS · VOLUMÉTRIE · TRAÇABILITÉ",
        ["Footer_Copyright"] = "© 2026 Pierre-Nicolas MARTIN · Licence GNU GPL v3",
        ["Done_Saved"] = "Projet enregistré",
        ["Done_Export"] = "Export terminé",
        ["Busy_Open"] = "Ouvrir",
        ["Empty_Title"] = "auditez vos systèmes de fichiers.",
        ["Greet_Morning"] = "Bonjour",
        ["Greet_Afternoon"] = "Bon après-midi",
        ["Greet_Evening"] = "Bonsoir",
        ["Greet_Night"] = "Bonne nuit",
        ["Btn_NewAudit"] = "Nouvel audit",
        ["Btn_OpenProject"] = "Ouvrir un projet",
        // — Configuration —
        ["Cfg_WinTitle"] = "Nouvel audit — MAAT",
        ["Cfg_Folder"] = "Dossier à auditer",
        ["Cfg_FolderHint"] = "Chemin local ou UNC (ex. C:\\Partages ou \\\\serveur\\partage).",
        ["Cfg_Browse"] = "Parcourir…",
        ["Cfg_Depth"] = "Profondeur d'analyse",
        ["Cfg_Numbering"] = "NUMÉROTATION DES NIVEAUX",
        ["Cfg_Root"] = "Racine",
        ["Cfg_Subfolder"] = "Sous-dossier",
        ["Cfg_DepthHint"] = "« Illimité » parcourt toute l'arborescence ; sinon, le numéro choisi est le dernier niveau inclus.",
        ["Cfg_Type"] = "Type d'audit",
        ["Cfg_TypeFolders"] = "Inclure les dossiers",
        ["Cfg_TypeFiles"] = "Inclure les dossiers et les fichiers",
        ["Cfg_LongHint"] = "(Temps d'exécution plus long)",
        ["Cfg_Content"] = "Contenu de l'audit",
        ["Cfg_ContentRights"] = "Analyser les droits",
        ["Cfg_ContentSize"] = "Analyser la volumétrie",
        ["Cfg_ContentBoth"] = "Analyser les droits et la volumétrie",
        ["Cfg_IdScope"] = "ÉTENDUE DES IDENTITÉS",
        ["Cfg_IncludeLocal"] = "Inclure les comptes locaux et intégrés",
        ["Cfg_IncludeLocalHint"] = "Décoché : seules les identités du domaine Active Directory sont auditées (exclut BUILTIN, AUTORITÉ NT, comptes de la machine, Tout le monde…).",
        ["Cfg_ExportHint"] = "Les exports CSV / HTML se font après l'audit (menu Fichier → Exporter).",
        ["Cfg_Start"] = "Lancer l'audit",
        ["Common_Cancel"] = "Annuler",
        ["Common_Close"] = "Fermer",
        ["Cfg_PathError"] = "Dossier introuvable ou inaccessible.",
        ["Cfg_PathInvalid"] = "Chemin invalide : {0}",
        // — Profondeur (options) —
        ["Depth_Unlimited"] = "♾  Illimité (toute l'arborescence)",
        ["Depth_RootOnly"] = "0  ·  Racine seulement",
        ["Depth_Level1"] = "{0}  ·  Racine + {0} sous-niveau",
        ["Depth_LevelN"] = "{0}  ·  Racine + {0} sous-niveaux",
        // — Progression —
        ["Prog_Title"] = "Audit en cours",
        ["Prog_Global"] = "PROGRESSION GLOBALE",
        ["Prog_Init"] = "Initialisation…",
        ["Prog_Estimating"] = "Estimation…",
        ["Prog_Done"] = "Terminé",
        ["Prog_Cancelled"] = "Annulé",
        ["Prog_Cancelling"] = "Annulation…",
        ["Prog_Error"] = "Erreur",
        ["Prog_ProjectLoaded"] = "Projet chargé",
        ["Prog_EtaLeft"] = "≈ {0} restant",
        ["Prog_Elapsed"] = "{0} écoulé",
        ["Step_Done"] = "terminé",
        ["Step_Pending"] = "en attente",
        ["Phase_EnumFolders"] = "Énumération de l'arborescence",
        ["Phase_EnumFiles"] = "Énumération des fichiers",
        ["Phase_ReadAcl"] = "Lecture des droits NTFS",
        ["Phase_ResolveAd"] = "Résolution des identités AD",
        ["Phase_Sizes"] = "Calcul de la volumétrie",
        ["Phase_Export"] = "Export",
        ["Phase_Default"] = "Traitement",
        // — Paramètres (résumé) —
        ["Param_Folders"] = "dossiers",
        ["Param_FoldersFiles"] = "dossiers + fichiers",
        ["Param_RightsSize"] = "droits + volumétrie",
        ["Param_Rights"] = "droits NTFS",
        ["Param_Size"] = "volumétrie",
        ["Param_DepthUnlimited"] = "profondeur illimitée",
        ["Param_DepthRoot"] = "racine seule",
        ["Param_Depth"] = "profondeur {0}",
        // — Busy / exports —
        ["Busy_ExportCsv"] = "Export CSV en cours",
        ["Busy_ExportHtml"] = "Génération du rapport HTML",
        ["Busy_Save"] = "Enregistrement du projet",
        ["Busy_Writing"] = "Écriture de {0}…",
        ["Busy_Wait"] = "Veuillez patienter…",
        ["Busy_BigHint"] = "Les très gros volumes peuvent prendre un moment.",
        ["Msg_ExportCsv"] = "Export CSV : {0}",
        ["Msg_ExportHtml"] = "Rapport HTML : {0}",
        ["Msg_Saved"] = "Projet enregistré : {0}",
        ["Dlg_SaveProject"] = "Enregistrer le projet MAAT",
        ["Dlg_OpenProject"] = "Ouvrir un projet MAAT",
        ["Filter_MaatOpen"] = "Projet MAAT (*.maat)|*.maat|Tous les fichiers (*.*)|*.*",
        ["Filter_Maat"] = "Projet MAAT (*.maat)|*.maat",
        ["Filter_Csv"] = "Fichier CSV (*.csv)|*.csv",
        ["Filter_Html"] = "Rapport HTML (*.html)|*.html",
        ["Filter_LogCsv"] = "Journal CSV (*.csv)|*.csv",
        ["Dlg_ExportCsv"] = "Exporter en CSV",
        ["Dlg_ExportHtml"] = "Exporter en rapport HTML",
        ["Dlg_PickFolder"] = "Sélectionner le dossier à auditer",
        // — Résultats / scan —
        ["Scan_AuditedPrefix"] = "Audité le",
        ["Scan_Search"] = "Rechercher un dossier, un fichier, un chemin…",
        ["Scan_SearchIdentities"] = "Rechercher une identité…",
        ["Scan_Folders"] = "DOSSIERS",
        ["Scan_TotalSize"] = "VOLUMÉTRIE TOTALE",
        ["Scan_Aces"] = "ENTRÉES ACL",
        ["Scan_Identities"] = "IDENTITÉS",
        ["Scan_AllRights"] = "Tous les droits",
        ["Scan_Explicit"] = "Explicites",
        ["Scan_Inherited"] = "Hérités",
        ["Scan_Loading"] = "Chargement…",
        ["Ace_Allow"] = "Autoriser",
        ["Ace_Deny"] = "Refuser",
        ["Ace_Inherited"] = "Hérité",
        ["Ace_Explicit"] = "Explicite",
        ["Ace_InheritedFrom"] = "Hérité de",
        ["Ace_MembersLabel"] = "Membres",
        ["Ace_MoreMembers"] = "+{0} autres…",
        ["Scan_SegFolders"] = "Dossiers",
        ["Scan_SegIdentities"] = "Identités",
        ["Scan_SelectFolder"] = "Sélectionnez un dossier pour afficher ses droits.",
        ["Scan_SelectIdentity"] = "Sélectionnez une identité pour afficher son détail.",
        ["Scan_ColType"] = "TYPE",
        ["Scan_ColIdentity"] = "IDENTITÉ",
        ["Scan_ColMembers"] = "MEMBRES",
        ["Scan_ColRights"] = "AUTORISATIONS",
        ["Scan_ColScope"] = "PORTÉE",
        ["Scan_ColInherit"] = "HÉRITAGE",
        ["Scan_ColPath"] = "CHEMIN",
        ["Scan_AceEntries"] = "{0} entrées ACL",
        ["Scan_InheritedN"] = "{0} héritées",
        ["Scan_ExplicitN"] = "{0} explicites",
        ["Scan_IdentitiesCount"] = "{0} identités",
        ["Scan_TypeGroup"] = "GROUPE",
        ["Scan_TypeAccount"] = "COMPTE",
        ["Scan_FolderCount"] = "{0} dossiers",
        ["Scan_PresentOn"] = "Présent sur {0} dossiers",
        ["Scan_MembersN"] = "{0} membres",
        ["Scan_NoMembers"] = "—",
        ["Scan_Locations"] = "EMPLACEMENTS",
        ["Scan_Range"] = "{0}–{1} sur {2}",
        ["Scan_PerPage"] = "Par page",
        ["Confirm_Title"] = "MAAT — Enregistrer le projet",
        ["Confirm_Discard"] = "L'audit en cours n'est pas enregistré.\nSouhaitez-vous enregistrer le projet avant de continuer ?",
        ["Name_Rights"] = "Audit_Droits",
        ["Name_RightsSize"] = "Audit_Droits_Volumetrie",
        ["Name_Size"] = "Audit_Volumetrie",
        // — Rapport d'analyse —
        ["Rep_WinTitle"] = "Rapport d'analyse de l'audit",
        ["Rep_Label"] = "RAPPORT D'ANALYSE",
        ["Rep_Title"] = "Synthèse de l'audit",
        ["Rep_FinishedOn"] = "Audit terminé le ",
        ["Rep_Issues"] = "ÉLÉMENTS NON AUDITÉS",
        ["Rep_AllAudited"] = "Aucun élément n'a été ignoré : l'audit est complet.",
        ["Rep_IssuesSummary"] = "{0} élément(s) non audité(s) — {1} erreur(s), {2} avertissement(s)",
        ["Rep_ExportLog"] = "Exporter le journal",
        ["Rep_DlgExportLog"] = "Exporter le journal d'audit",
        ["Rep_LogExported"] = "Journal exporté : {0}",
        ["Sev_Error"] = "Erreur",
        ["Sev_Warn"] = "Avertissement",
        ["Rep_LogHeader"] = "Horodatage;Gravité;Motif;Chemin",
        ["Rep_FinishedMeta"] = "Terminé le {0}",
        ["Rep_DurationMeta"] = "Durée {0}",
        ["Verdict_success"] = "Terminé",
        ["Verdict_warning"] = "Terminé avec observations",
        ["Verdict_error"] = "Terminé avec erreurs",
        ["Rep_Sig_DeniedTitle"] = "Accès refusé",
        ["Rep_Sig_DeniedSub"] = "Dossiers non lus",
        ["Rep_Sig_JunctionTitle"] = "Jonctions ignorées",
        ["Rep_Sig_JunctionSub"] = "Liens non suivis",
        ["Rep_Sig_ReadTitle"] = "Erreur de lecture",
        ["Rep_Sig_ReadSub"] = "Lecture échouée",
        ["Rep_Sig_AdTitle"] = "Active Directory",
        ["Rep_Sig_AdOn"] = "Disponible — identités résolues",
        ["Rep_Sig_AdOff"] = "Indisponible — SID non résolus",
        ["Rep_CountItems"] = "{0} éléments",
        ["Rep_CountErrors"] = "{0} erreur(s)",
        ["Rep_CountWarns"] = "{0} avertissement(s)",
        ["Rep_IssuesExplain"] = "Ces éléments n'ont pas pu être inspectés. Les accès refusés peuvent masquer des droits non conformes — passez-les en revue.",
        ["Rep_Col_Reason"] = "MOTIF",
        ["Rep_Col_Path"] = "CHEMIN",
        ["Rep_Col_Severity"] = "GRAVITÉ",
        ["Rep_ShowRemaining"] = "Afficher les {0} éléments restants",
        ["Rep_Confidential"] = "Les résultats peuvent contenir des informations sensibles ou confidentielles.",
        ["Log_AccessDenied"] = "Accès refusé",
        ["Log_PathNotFound"] = "Chemin introuvable",
        ["Log_ReparseSkipped"] = "Jonction / lien ignoré",
        ["Log_ReadError"] = "Erreur de lecture",
        ["Log_AclUnreadable"] = "ACL illisible",
        ["Log_AceError"] = "Erreur sur une ACE",
        ["Log_AdResolution"] = "Résolution Active Directory",
        ["Log_Other"] = "Évènement",
        // — À propos —
        ["About_Tagline"] = "Audit avancé de systèmes de fichiers : droits NTFS (héritage, Autoriser/Refuser, groupes AD) et volumétrie.",
        ["About_License"] = "LICENCE GNU GPL v3",
        ["About_LicenseBody"] = "Logiciel libre redistribuable selon les termes de la GPLv3 — ",
        ["About_Warranty"] = "Ce programme est fourni « en l'état », sans aucune garantie, dans la mesure permise par la loi. L'auteur ne saurait être tenu responsable des dommages résultant de son utilisation.",
        ["About_Version"] = "Version {0}",
        ["About_WinTitle"] = "À propos de MAAT",
        ["About_Kicker"] = "À PROPOS",
        ["About_Subtitle"] = "Monitoring et Audit des Accès pour la Traçabilité",
        ["About_Edition"] = "ÉDITION STABLE",
        ["About_Cap1Label"] = "DROITS",
        ["About_Cap1Value"] = "ACL NTFS & AD",
        ["About_Cap2Label"] = "VOLUMÉTRIE",
        ["About_Cap2Value"] = "Tailles agrégées",
        ["About_Cap3Label"] = "PLATEFORME",
        ["About_Cap3Value"] = "Windows · WPF",
        ["About_RightsReserved"] = "TOUS DROITS RÉSERVÉS · GPLV3",
        // — Guide —
        ["Guide_WinTitle"] = "Guide d'utilisation — MAAT",
        ["Guide_Search"] = "Rechercher dans le guide…",
        ["Guide_Note"] = "NOTE",
        ["Guide_HdrLabel"] = "AIDE",
        ["Guide_HdrTitle"] = "Guide d'utilisation",
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // — Menu —
        ["Menu_File"] = "File",
        ["Menu_NewAudit"] = "New audit…",
        ["Menu_OpenProject"] = "Open project…",
        ["Menu_ExportTo"] = "Export to",
        ["Menu_ExportHtml"] = "HTML report…",
        ["Menu_ExportCsv"] = "CSV…",
        ["Menu_SaveProject"] = "Save project as…",
        ["Menu_Quit"] = "Quit",
        ["Menu_Preferences"] = "Preferences",
        ["Menu_Display"] = "Appearance",
        ["Menu_ThemeAuto"] = "Auto (system)",
        ["Menu_ThemeLight"] = "Light theme",
        ["Menu_ThemeDark"] = "Dark theme",
        ["Menu_Language"] = "Language",
        ["Menu_LangAuto"] = "Auto (system)",
        ["Menu_Help"] = "Help",
        ["Menu_Guide"] = "User guide…",
        ["Menu_About"] = "About…",
        // — Header / home —
        ["Win_Title"] = "MAAT — File system audit",
        ["Access_All"] = "All items",
        ["Header_Subtitle"] = "Monitoring and Access Auditing for Traceability",
        ["Header_Tag"] = "NTFS AUDIT · VOLUMETRY · TRACEABILITY",
        ["Footer_Copyright"] = "© 2026 Pierre-Nicolas MARTIN · GNU GPL v3 License",
        ["Done_Saved"] = "Project saved",
        ["Done_Export"] = "Export complete",
        ["Busy_Open"] = "Open",
        ["Empty_Title"] = "audit your file systems.",
        ["Greet_Morning"] = "Good morning",
        ["Greet_Afternoon"] = "Good afternoon",
        ["Greet_Evening"] = "Good evening",
        ["Greet_Night"] = "Good night",
        ["Btn_NewAudit"] = "New audit",
        ["Btn_OpenProject"] = "Open project",
        // — Configuration —
        ["Cfg_WinTitle"] = "New audit — MAAT",
        ["Cfg_Folder"] = "Folder to audit",
        ["Cfg_FolderHint"] = "Local or UNC path (e.g. C:\\Shares or \\\\server\\share).",
        ["Cfg_Browse"] = "Browse…",
        ["Cfg_Depth"] = "Analysis depth",
        ["Cfg_Numbering"] = "LEVEL NUMBERING",
        ["Cfg_Root"] = "Root",
        ["Cfg_Subfolder"] = "Subfolder",
        ["Cfg_DepthHint"] = "\"Unlimited\" walks the whole tree; otherwise the chosen number is the last level included.",
        ["Cfg_Type"] = "Audit type",
        ["Cfg_TypeFolders"] = "Include folders",
        ["Cfg_TypeFiles"] = "Include folders and files",
        ["Cfg_LongHint"] = "(Longer execution time)",
        ["Cfg_Content"] = "Audit content",
        ["Cfg_ContentRights"] = "Analyze permissions",
        ["Cfg_ContentSize"] = "Analyze volumetry",
        ["Cfg_ContentBoth"] = "Analyze permissions and volumetry",
        ["Cfg_IdScope"] = "IDENTITY SCOPE",
        ["Cfg_IncludeLocal"] = "Include local and built-in accounts",
        ["Cfg_IncludeLocalHint"] = "Unchecked: only Active Directory domain identities are audited (excludes BUILTIN, NT AUTHORITY, machine accounts, Everyone…).",
        ["Cfg_ExportHint"] = "CSV / HTML exports are done after the audit (File → Export).",
        ["Cfg_Start"] = "Start audit",
        ["Common_Cancel"] = "Cancel",
        ["Common_Close"] = "Close",
        ["Cfg_PathError"] = "Folder not found or inaccessible.",
        ["Cfg_PathInvalid"] = "Invalid path: {0}",
        // — Depth —
        ["Depth_Unlimited"] = "♾  Unlimited (whole tree)",
        ["Depth_RootOnly"] = "0  ·  Root only",
        ["Depth_Level1"] = "{0}  ·  Root + {0} sublevel",
        ["Depth_LevelN"] = "{0}  ·  Root + {0} sublevels",
        // — Progress —
        ["Prog_Title"] = "Audit in progress",
        ["Prog_Global"] = "OVERALL PROGRESS",
        ["Prog_Init"] = "Initializing…",
        ["Prog_Estimating"] = "Estimating…",
        ["Prog_Done"] = "Done",
        ["Prog_Cancelled"] = "Cancelled",
        ["Prog_Cancelling"] = "Cancelling…",
        ["Prog_Error"] = "Error",
        ["Prog_ProjectLoaded"] = "Project loaded",
        ["Prog_EtaLeft"] = "≈ {0} left",
        ["Prog_Elapsed"] = "{0} elapsed",
        ["Step_Done"] = "done",
        ["Step_Pending"] = "pending",
        ["Phase_EnumFolders"] = "Enumerating the tree",
        ["Phase_EnumFiles"] = "Enumerating files",
        ["Phase_ReadAcl"] = "Reading NTFS permissions",
        ["Phase_ResolveAd"] = "Resolving AD identities",
        ["Phase_Sizes"] = "Computing sizes",
        ["Phase_Export"] = "Export",
        ["Phase_Default"] = "Processing",
        // — Parameters summary —
        ["Param_Folders"] = "folders",
        ["Param_FoldersFiles"] = "folders + files",
        ["Param_RightsSize"] = "permissions + size",
        ["Param_Rights"] = "NTFS permissions",
        ["Param_Size"] = "size",
        ["Param_DepthUnlimited"] = "unlimited depth",
        ["Param_DepthRoot"] = "root only",
        ["Param_Depth"] = "depth {0}",
        // — Busy / exports —
        ["Busy_ExportCsv"] = "Exporting CSV",
        ["Busy_ExportHtml"] = "Generating HTML report",
        ["Busy_Save"] = "Saving project",
        ["Busy_Writing"] = "Writing {0}…",
        ["Busy_Wait"] = "Please wait…",
        ["Busy_BigHint"] = "Very large volumes may take a while.",
        ["Msg_ExportCsv"] = "CSV export: {0}",
        ["Msg_ExportHtml"] = "HTML report: {0}",
        ["Msg_Saved"] = "Project saved: {0}",
        ["Dlg_SaveProject"] = "Save MAAT project",
        ["Dlg_OpenProject"] = "Open a MAAT project",
        ["Filter_MaatOpen"] = "MAAT project (*.maat)|*.maat|All files (*.*)|*.*",
        ["Filter_Maat"] = "MAAT project (*.maat)|*.maat",
        ["Filter_Csv"] = "CSV file (*.csv)|*.csv",
        ["Filter_Html"] = "HTML report (*.html)|*.html",
        ["Filter_LogCsv"] = "CSV log (*.csv)|*.csv",
        ["Dlg_ExportCsv"] = "Export to CSV",
        ["Dlg_ExportHtml"] = "Export to HTML report",
        ["Dlg_PickFolder"] = "Select the folder to audit",
        // — Results / scan —
        ["Scan_AuditedPrefix"] = "Audited on",
        ["Scan_Search"] = "Search a folder, a file, a path…",
        ["Scan_SearchIdentities"] = "Search an identity…",
        ["Scan_Folders"] = "FOLDERS",
        ["Scan_TotalSize"] = "TOTAL SIZE",
        ["Scan_Aces"] = "ACL ENTRIES",
        ["Scan_Identities"] = "IDENTITIES",
        ["Scan_AllRights"] = "All permissions",
        ["Scan_Explicit"] = "Explicit",
        ["Scan_Inherited"] = "Inherited",
        ["Scan_Loading"] = "Loading…",
        ["Ace_Allow"] = "Allow",
        ["Ace_Deny"] = "Deny",
        ["Ace_Inherited"] = "Inherited",
        ["Ace_Explicit"] = "Explicit",
        ["Ace_InheritedFrom"] = "Inherited from",
        ["Ace_MembersLabel"] = "Members",
        ["Ace_MoreMembers"] = "+{0} more…",
        ["Scan_SegFolders"] = "Folders",
        ["Scan_SegIdentities"] = "Identities",
        ["Scan_SelectFolder"] = "Select a folder to view its permissions.",
        ["Scan_SelectIdentity"] = "Select an identity to view its detail.",
        ["Scan_ColType"] = "TYPE",
        ["Scan_ColIdentity"] = "IDENTITY",
        ["Scan_ColMembers"] = "MEMBERS",
        ["Scan_ColRights"] = "PERMISSIONS",
        ["Scan_ColScope"] = "SCOPE",
        ["Scan_ColInherit"] = "INHERITANCE",
        ["Scan_ColPath"] = "PATH",
        ["Scan_AceEntries"] = "{0} ACL entries",
        ["Scan_InheritedN"] = "{0} inherited",
        ["Scan_ExplicitN"] = "{0} explicit",
        ["Scan_IdentitiesCount"] = "{0} identities",
        ["Scan_TypeGroup"] = "GROUP",
        ["Scan_TypeAccount"] = "ACCOUNT",
        ["Scan_FolderCount"] = "{0} folders",
        ["Scan_PresentOn"] = "Present on {0} folders",
        ["Scan_MembersN"] = "{0} members",
        ["Scan_NoMembers"] = "—",
        ["Scan_Locations"] = "LOCATIONS",
        ["Scan_Range"] = "{0}–{1} of {2}",
        ["Scan_PerPage"] = "Per page",
        ["Confirm_Title"] = "MAAT — Save project",
        ["Confirm_Discard"] = "The current audit is not saved.\nDo you want to save the project before continuing?",
        ["Name_Rights"] = "Audit_Permissions",
        ["Name_RightsSize"] = "Audit_Permissions_Size",
        ["Name_Size"] = "Audit_Size",
        // — Analysis report —
        ["Rep_WinTitle"] = "Audit analysis report",
        ["Rep_Label"] = "ANALYSIS REPORT",
        ["Rep_Title"] = "Audit summary",
        ["Rep_FinishedOn"] = "Audit finished on ",
        ["Rep_Issues"] = "ITEMS NOT AUDITED",
        ["Rep_AllAudited"] = "No item was skipped: the audit is complete.",
        ["Rep_IssuesSummary"] = "{0} item(s) not audited — {1} error(s), {2} warning(s)",
        ["Rep_ExportLog"] = "Export log",
        ["Rep_DlgExportLog"] = "Export audit log",
        ["Rep_LogExported"] = "Log exported: {0}",
        ["Sev_Error"] = "Error",
        ["Sev_Warn"] = "Warning",
        ["Rep_LogHeader"] = "Timestamp;Severity;Reason;Path",
        ["Rep_FinishedMeta"] = "Finished on {0}",
        ["Rep_DurationMeta"] = "Duration {0}",
        ["Verdict_success"] = "Completed",
        ["Verdict_warning"] = "Completed with observations",
        ["Verdict_error"] = "Completed with errors",
        ["Rep_Sig_DeniedTitle"] = "Access denied",
        ["Rep_Sig_DeniedSub"] = "Folders not read",
        ["Rep_Sig_JunctionTitle"] = "Junctions skipped",
        ["Rep_Sig_JunctionSub"] = "Links not followed",
        ["Rep_Sig_ReadTitle"] = "Read error",
        ["Rep_Sig_ReadSub"] = "Read failed",
        ["Rep_Sig_AdTitle"] = "Active Directory",
        ["Rep_Sig_AdOn"] = "Available — identities resolved",
        ["Rep_Sig_AdOff"] = "Unavailable — SIDs not resolved",
        ["Rep_CountItems"] = "{0} items",
        ["Rep_CountErrors"] = "{0} error(s)",
        ["Rep_CountWarns"] = "{0} warning(s)",
        ["Rep_IssuesExplain"] = "These items could not be inspected. Access-denied folders may hide non-compliant rights — review them.",
        ["Rep_Col_Reason"] = "REASON",
        ["Rep_Col_Path"] = "PATH",
        ["Rep_Col_Severity"] = "SEVERITY",
        ["Rep_ShowRemaining"] = "Show the {0} remaining items",
        ["Rep_Confidential"] = "Results may contain sensitive or confidential information.",
        ["Log_AccessDenied"] = "Access denied",
        ["Log_PathNotFound"] = "Path not found",
        ["Log_ReparseSkipped"] = "Junction / link skipped",
        ["Log_ReadError"] = "Read error",
        ["Log_AclUnreadable"] = "Unreadable ACL",
        ["Log_AceError"] = "ACE error",
        ["Log_AdResolution"] = "Active Directory resolution",
        ["Log_Other"] = "Event",
        // — About —
        ["About_Tagline"] = "Advanced file-system auditing: NTFS permissions (inheritance, Allow/Deny, AD groups) and volumetry.",
        ["About_License"] = "GNU GPL v3 LICENSE",
        ["About_LicenseBody"] = "Free software redistributable under the terms of the GPLv3 — ",
        ["About_Warranty"] = "This program is provided \"as is\", without any warranty, to the extent permitted by law. The author shall not be held liable for any damage resulting from its use.",
        ["About_Version"] = "Version {0}",
        ["About_WinTitle"] = "About MAAT",
        ["About_Kicker"] = "ABOUT",
        ["About_Subtitle"] = "Monitoring and Access Auditing for Traceability",
        ["About_Edition"] = "STABLE EDITION",
        ["About_Cap1Label"] = "PERMISSIONS",
        ["About_Cap1Value"] = "NTFS ACL & AD",
        ["About_Cap2Label"] = "VOLUMETRY",
        ["About_Cap2Value"] = "Aggregated sizes",
        ["About_Cap3Label"] = "PLATFORM",
        ["About_Cap3Value"] = "Windows · WPF",
        ["About_RightsReserved"] = "ALL RIGHTS RESERVED · GPLV3",
        // — Guide —
        ["Guide_WinTitle"] = "User guide — MAAT",
        ["Guide_Search"] = "Search the guide…",
        ["Guide_Note"] = "NOTE",
        ["Guide_HdrLabel"] = "HELP",
        ["Guide_HdrTitle"] = "User guide",
    };
}